### ISSUE TITLE
Bug in setup.cfg

### ISSUE THREAD

**Issue by eduardo-rodrigues** [lovaslin/pyBumpHunter#18]
The line `python_requires = >=3.5` should for sure be `python_requires >=3.5` ;-).

**Comment by eduardo-rodrigues** [comment]
BTW, it should also be `classifiers` instead of `classifier`. Better that you check this config file carefully ...

**Comment by lovaslin** [comment]
Thank you for reporting this issue.
I corrected the `classifiers` and added some.
However, for the `python_requires` line, I will keep it as it is.
From what I saw in other projects, it should be written this way.
It also seems that PyPI recognizes it correctly.

**Comment by eduardo-rodrigues** [comment]
That's weird, i never came across such a strange syntax `= >=`.

BTW, why not refer to the issue when creating the related PR, which I actually do not see? If you say "Closes #<N>" on the PR the related issue N will be closed automatically once the PR gets merged.
